# Generated by Django 5.0.4 on 2024-04-16 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashbord', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
